version: "3.3"
services:
  lobby:
    build:
      dockerfile: ../../../deployment/Dockerfile
      context: ../lobby-impl/target/universal
    restart: always
    ports:
      - 9000:9000
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
  cassandra:
    image: cassandra
    ports:
      - 9042:9042
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G